name: Playwright bench

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Code version"
        required: true
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit
      cpu_tag:
        description: "CPU type for job"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - E5645
      git_tag:
        description: "Code version"
        required: true
        type: choice
        options:
          - V1
          - V2
          - V3
          - V4

jobs:
  run-wasm-benchmark:
    runs-on: ${{ inputs.cpu_tag }}
    steps:
      - name: Checkout benchmarks branch
        uses: actions/checkout@v4
        with:
          ref: benchmarks
          fetch-depth: 0

      - name: Save existing benchmark file
        run: mkdir -p tmp_results && cp results/benchmark_results_wasm.csv tmp_results/ || true

      - name: Checkout code from tag
        run: |
          git fetch origin ${{ inputs.git_tag }}
          git worktree add ../code_to_test ${{ inputs.git_tag }}

      - name: Restore old benchmark results
        run: mkdir -p results && cp tmp_results/benchmark_results_wasm.csv results/ || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rust-src

      - name: Build Rust WASM and React Application
        run: |
          cargo install wasm-pack
          cd ../code_to_test/wasm && wasm-pack build --target web --out-dir ../../src/wasm
          cd ../../src && npm install && npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Vite preview server
        run: |
          nohup npm run preview &

      - name: Wait for server
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:4173 >/dev/null; then
              echo "Vite preview server is live!"
              break
            fi
            echo "Waiting for Vite preview..."
            sleep 2
          done

      - name: Run Playwright tests
        run: |
          if [ "${{ inputs.browser }}" == "all" ]; then
            npx playwright test speed-remote
          else
            npx playwright test speed-remote --project ${{ inputs.browser }}
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Commit and push benchmark results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          create_branch: true
          branch: "benchmarks"
          commit_message: "chore: update benchmark results"
          file_pattern: "results/benchmark_results_*.csv"
